<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>

        <IsPackable>false</IsPackable>

        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="nunit" Version="4.4.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="5.1.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OsdpSpy\OsdpSpy.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Annotators\" />
      <Folder Include="Clear\" />
      <Folder Include="Decoders\" />
      <Folder Include="Import\" />
      <Folder Include="List\" />
      <Folder Include="Serial\" />
    </ItemGroup>

</Project>
